In [3]:
import numpy as np

In [4]:
 
arr = np.array([2,5,6,8], dtype = int)
print(arr)
# [2 5 6 8]
print(type(arr))
# class 'numpy.ndarray'
print(np.result_type(arr))
# int32 
 


[2 5 6 8]
<class 'numpy.ndarray'>
int32


In [5]:
c=np.arange(1,10,0.9)
c

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [13]:
d=np.linspace(0,200,11)
`d` is creating an array of 11 evenly spaced values between 0 and 200 using NumPy's `linspace` function.
d

array([  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180., 200.])

#Matrix Creation

Moving ahead, let's learn creation of matrix using NumPy. This task can be achieved in many ways as listed below:

Method I: Use NumPy array to form a matrix

Method II: Use NumPy's inbuilt matrix function

Method III: Use miscellaneous functions such as ones(), zeroes(), etc.

